Allows users to adjust Message bubble size
atsign-foundation/at_widgets pull request #73
Opened 2021-07-14 01:22 UTC by FredeEmnetu

**-What I did:**
 Created parameters for chat screen so that the message bubbles are customizable

**- How I did it**
Created instances "bubble_height" and "bubble_width" in both Message Bubble classes and
instead of edgeinsets.all(10) I set them to be a parameter and used those parameters in chatscreen.

bubble_height: widget.bubble_height,
bubble_width: widget.bubble_width,

**- How to verify it**
Run the chatscreen widget class and attempt to adjust the bubble sizes using bubble_width and bubble_height parameters

**- Description for the changelog**

 Created parameters for chat screen so that the message bubbles are customizable

2021-07-20 18:29 UTC, XavierChanth commented on at_chat_flutter/lib/screens/chat_screen.dart
> +// import 'package:at_chat_flutter/widgets/incoming_message_bubble.dart';
This line should be removed

2021-07-20 19:32 UTC, XavierChanth requested changes
The code needs to be formatted to match the standards in the rest of the library:

- bubble_height and bubble_width:
  - These are padding sizes, should probably be called bubbleVerticalPadding or bubbleHeightPadding.
  - Should use camel case
- chat_screen.dart has a commented, duplicate import
- Added arguments to constructors should be on their own line:
  - chat_screen.dart line 42
  - outgoing_message_bubble.dart line 19
  - incoming_message_bubble.dart line 19

2021-07-21 06:44 UTC, sachins-geekyants commented
@FredeEmnetu thanks for these enhancements.
Can you please add changes requested by @XavierChanth , rest looks fine to me.

2021-07-21 06:47 UTC, sachins-geekyants reviewed
@FredeEmnetu  Can you please add changes requested by @XavierChanth , rest looks good to me.

2022-06-17 12:30 UTC, xavierchanth commented
Closing this because it is stale

2022-06-17 12:30 UTC, closed without merging