deps: Update and fix all dependencies
atsign-foundation/at_widgets pull request #741
Opened 2023-09-13 09:26 UTC by XavierChanth

**- What I did**

- Updated all dependencies in each package, and then rolled back a handful due to dependency constraints in other places
  - (intl, meta - pinned by the flutter sdk)
  - (collection, mocktail - external dependencies)
- Fixed the breaking changes in each of the packages

TODO:
- [ ] Determine which packages should be considered as having breaking changes 
- [ ] Update changelogs
- [ ] Increase version numbers

**- How I did it**

**- How to verify it**

**- Description for the changelog**

2023-09-13 09:32 UTC, XavierChanth commented
I'm going to leave comments on each pubspec.yaml with which dependencies had major version changes, and then we can determine whether we should consider those packages as breaking.

2023-09-13 09:43 UTC, XavierChanth commented on packages/at_backupkey_flutter/lib/widgets/backup_key_widget.dart
> +          var size = MediaQuery.of(context).size;
Wrapped with a mounted check

2023-09-13 09:43 UTC, XavierChanth commented on packages/at_backupkey_flutter/lib/widgets/backup_key_widget.dart
>          if (context.mounted) {
getSavePath was removed in 1.0.0 of path_selector, so I replaced it with the getSaveLocation

2023-09-13 09:44 UTC, XavierChanth commented on melos.yaml
> +  - packages/*/*example
Explicitly identified the packages and examples just in case there are further nested pubspec.yaml files which we might want to ignore in melos

2023-09-13 09:45 UTC, XavierChanth commented on packages/at_backupkey_flutter/pubspec.yaml
> +  permission_handler: ^11.0.0
Permission handler ^10.4.1 -> ^11.0.0

2023-09-13 09:45 UTC, XavierChanth commented on packages/at_backupkey_flutter/pubspec.yaml
> +  file_selector: ^1.0.1
file_selector ^0.9.5 -> ^1.0.1

2023-09-13 09:48 UTC, XavierChanth commented on packages/at_contacts_group_flutter/pubspec.yaml
> -  file_selector_macos: '>=0.8.2 <1.0.0'
file_selector '>=0.8.4+1 <2.0.0' -> ^1.0.1

2023-09-13 09:54 UTC, XavierChanth commented on packages/at_follows_flutter/pubspec.yaml
> -  permission_handler: ^9.2.0
permission_handler ^9.2.0 -> ^11.0.0

2023-09-13 09:55 UTC, XavierChanth commented on packages/at_invitation_flutter/example/lib/main.dart
> +                        final result = await AtOnboarding.onboard(
Uptake of the new onboarding widget

2023-09-13 09:56 UTC, XavierChanth commented on packages/at_invitation_flutter/pubspec.yaml
> -  pin_code_fields: ^7.3.0
pin_code_fields ^7.3.0 -> ^8.0.1

2023-09-13 09:57 UTC, XavierChanth commented on packages/at_location_flutter/pubspec.yaml
> -  geolocator: ^9.0.2
geolocator ^9.0.2 -> ^10.0.1

2023-09-13 09:58 UTC, XavierChanth commented on packages/at_login_flutter/example/lib/main.dart
> +                  final result = await AtOnboarding.onboard(
Wrapped with a context.mounted check

2023-09-13 09:59 UTC, XavierChanth commented on packages/at_login_flutter/lib/services/notification_service.dart
>    }
The _notificationsPlugin.initialize API changed, I'm not sure if this is correct, I will be investigating this one for breaking changes.

2023-09-13 09:59 UTC, XavierChanth commented on packages/at_login_flutter/lib/services/notification_service.dart
> +    DarwinInitializationSettings(
IOSInitializationSettings is now DarwinInitializationSettings

2023-09-13 10:00 UTC, XavierChanth commented on packages/at_login_flutter/lib/services/notification_service.dart
> +      channelDescription: 'CHANNEL_DESCRIPTION',
This changed from a positional argument to a named one

2023-09-13 10:00 UTC, XavierChanth commented on packages/at_login_flutter/pubspec.yaml
> +  flutter_local_notifications: ^15.1.1
flutter_local_notifications ^5.0.0+1 -> ^15.1.1 
Yes, you're reading that right... 10 major versions...

2023-09-13 10:01 UTC, xavierchanth commented on packages/at_login_flutter/pubspec.yaml
> -  file_picker: ^4.0.0
file_picker ^4.0.0 -> ^5.5.0

2023-09-13 10:01 UTC, xavierchanth commented on packages/at_login_flutter/pubspec.yaml
> +  permission_handler: ^11.0.0
permission_handler ^8.1.2 -> ^11.0.0

2023-09-13 10:01 UTC, XavierChanth commented on packages/at_login_flutter/pubspec.yaml
> +  http: ^1.1.0
http ^0.13.3 -> ^1.1.0

2023-09-13 10:02 UTC, XavierChanth commented on packages/at_login_flutter/pubspec.yaml
> +  provider: ^6.0.5
provider ^5.0.0 -> ^6.0.5

2023-09-13 10:02 UTC, XavierChanth commented on packages/at_login_flutter/pubspec.yaml
> -  basic_utils: ^3.3.2
basic_utils ^3.3.2 -> ^5.6.1

2023-09-13 10:03 UTC, XavierChanth commented on packages/at_notify_flutter/pubspec.yaml
> +  flutter_local_notifications: ^15.1.1
flutter_local_notifications ^14.1.1 -> ^15.1.1

2023-09-13 10:04 UTC, XavierChanth commented on packages/at_onboarding_flutter/pubspec.yaml
> -  file_selector: ^1.0.0
file_selector '>=0.8.4+3	<=1.0.0' overridden to ^1.0.0 -> ^1.1.0 ...

2023-09-13 10:06 UTC, XavierChanth commented on packages/at_onboarding_flutter/pubspec.yaml
> +  permission_handler: ^11.0.0
permission_handler ^10.4.3 -> ^11.0.0

2023-09-13 10:07 UTC, XavierChanth commented on packages/at_events_flutter/pubspec.yaml
> -  geolocator: ^9.0.2
geolocator ^9.0.2 -> ^10.0.1
... does events even use geolocator???

2023-09-13 10:08 UTC, XavierChanth commented on packages/at_onboarding_flutter/pubspec.yaml
I made the versioning in at_onboarding_flutter very strict... maybe I can lower back the versions for some of these, how do we feel about that?

2023-09-13 10:10 UTC, XavierChanth commented on packages/at_sync_ui_flutter/test/at_sync_ui_flutter_test.dart
> +      AtClientManager.getInstance().atClient.syncService = mockSyncService;
Updated to use the non-deprecated API

2023-09-19 09:50 UTC, sachins-geekyants commented
> I'm going to leave comments on each pubspec.yaml with which dependencies had major version changes, and then we can determine whether we should consider those packages as breaking.

@XavierChanth IMO if any of the major dependency update causes change in our package api then we should be considering for a major version change else minor should be fine.

2023-09-21 07:45 UTC, XavierChanth commented
Package versions to be published with this PR:
at_backupkey_flutter: 4.0.11
at_chat_flutter: 3.0.10
at_contacts_flutter: 4.0.12
at_contacts_group_flutter: 4.0.14
at_events_flutter: 3.1.12
at_follows_flutter: 3.0.10
at_invitation_flutter: 2.0.1
at_location_flutter: 3.1.10
at_login_flutter: 0.0.2
at_notify_flutter: 1.0.8
at_onboarding_flutter: 6.1.4
at_sync_ui_flutter: 1.0.10
at_theme_flutter: 1.0.6

2023-09-21 08:28 UTC, sachins-geekyants commented on packages/at_onboarding_flutter/example/pubspec.yaml
> +  at_onboarding_flutter: ^6.1.3
`at_onboarding_flutter ` should be coming from local path.

2023-09-21 08:31 UTC, sachins-geekyants commented on packages/at_sync_ui_flutter/CHANGELOG.md
> +
Last released version of sync package is `1.0.8`.
`1.0.10` changes can be  combined with `1.0.9`

2023-09-21 08:40 UTC, cpswan requested changes
Great work @XavierChanth 

Mostly LGTM, but @sachins-geekyants is right about at_onboarding_flutter needing to be local

2023-09-21 08:41 UTC, XavierChanth commented
@sachins-geekyants @cpswan both have been fixed

2023-09-21 08:43 UTC, cpswan submitted a review, later dismissed

2023-09-21 08:44 UTC, sachins-geekyants submitted a review, later dismissed

2023-09-21 08:44 UTC, XavierChanth commented
Please hold off on merging, until all publishing has been complete, just in case there are further changes that need to be added and reviewed

2023-09-21 08:47 UTC, XavierChanth commented
- [ ] at_backupkey_flutter: 4.0.11
- [ ] at_chat_flutter: 3.0.10
- [ ] at_contacts_flutter: 4.0.12
- [ ] at_contacts_group_flutter: 4.0.14
- [ ] at_events_flutter: 3.1.12
- [ ] at_follows_flutter: 3.0.10
- [ ] at_invitation_flutter: 2.0.1
- [ ] at_location_flutter: 3.1.10
- [ ] at_login_flutter: 0.0.2
- [ ] at_notify_flutter: 1.0.8
- [ ] at_onboarding_flutter: 6.1.4
- [ ] at_sync_ui_flutter: 1.0.10
- [ ] at_theme_flutter: 1.0.6

2023-09-21 09:06 UTC, cpswan approved these changes

2023-09-21 10:28 UTC, merged