fix: atSign activation
atsign-foundation/at_widgets pull request #948
Opened 2024-11-26 18:30 UTC by XavierChanth

**- What I did**

- Changed activation references to use onboard method instead of authenticate method
- Fixed a regression to revert back to the original atSign when activation fails

**- How I did it**

**- How to verify it**

- Ran the example app with a valid api key in .env
- Activated an atSign by OTP

**- Description for the changelog**
fix: atSign activation

2024-11-26 18:33 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_home_screen.dart
> +
Actual change for this file is here, the rest is formatting from 120 to 80, as this is a published package.

2024-11-26 18:33 UTC, xavierchanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_home_screen.dart
> +
Actual change for this file is here, the rest is formatting from 120 to 80, as this is a published package. (559 old file : 604 new file)

2024-11-26 18:35 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_activate_screen.dart
> +      );
change to onboard

2024-11-26 18:35 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_activate_screen.dart
> +
revert to previous on a failed activation (authSuccess + teapot at this point is considered a timeout failure)

2024-11-26 18:36 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_generate_screen.dart
> +
Same as above

2024-11-26 18:36 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_generate_screen.dart
> +      if (authResponse == AtOnboardingResponseStatus.serverNotReached) {
Same as revert above, slightly different semantic structure in this part of the code, so the change looks different

2024-11-26 18:37 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_generate_screen.dart
> +      } else if (authResponse != AtOnboardingResponseStatus.authSuccess) {
breaking the if-else chain requires an explicit check for non-success on our catch-all error check

2024-11-26 18:38 UTC, XavierChanth commented on packages/at_onboarding_flutter/lib/screen/at_onboarding_home_screen.dart
> +      AtOnboardingLocalizations.current.error_processing_files;
This file was misformatted, I've commented the actual changes around line 580

2024-11-26 19:09 UTC, CurtlyCritchlow approved these changes, later dismissed
lgtm

2024-12-02 12:09 UTC, gkc approved these changes
LGTM

2024-12-02 12:11 UTC, gkc requested changes
Oops spoke too soon ... one of the 'stable' checks is failing https://github.com/atsign-foundation/at_widgets/actions/runs/12036898481/job/33559158729?pr=948

```
Analyzing at_onboarding_flutter...                              

warning • Unused import: 'package:at_auth/at_auth.dart' • lib/screen/at_onboarding_activate_screen.dart:4:8 • unused_import
warning • Unused import: 'package:at_client_mobile/at_client_mobile.dart' • lib/screen/at_onboarding_activate_screen.dart:5:8 • unused_import
warning • The value of the local variable 'cramSecret' isn't used • lib/screen/at_onboarding_generate_screen.dart:458:12 • unused_local_variable
```

2025-01-06 15:18 UTC, Zambrella commented
Added some additional fixes:
- Removed stuck spinner after entering OTP
- Fixed navigation bug that failed to show user the backup keys screen
- Removed unneeded imports

2025-01-07 18:26 UTC, gkc approved these changes

2025-01-08 13:44 UTC, merged